#!/bin/csh -f

################################################################################
# Open SpyGlass GUI for Debug 
################################################################################
# RTL project file name
set RTL_PRJ_FILE = ./bit_slice/rtl_sg_setup/bit_slice.prj

########################################
spyglass -project ${RTL_PRJ_FILE} & 

########################################
