#!/bin/csh -f

################################################################################
# Run lint at RTL with SpyGlass
################################################################################

# RTL project file name
set RTL_PRJ_FILE = ./bit_slice/rtl_sg_setup/bit_slice.prj

########################################

spyglass -project ${RTL_PRJ_FILE} -goal lint/lint_rtl $*

########################################
