set_operating_conditions tt0p85v125c

set_voltage -object_list  SS.power 0.85
set_voltage -object_list  SSL.power 0.78
set_voltage -object_list SS.ground 0.0

set_voltage -object_list  slice_0/SS.ground 0.0
set_voltage -object_list  slice_1/SS.ground 0.0
set_voltage -object_list  slice_2/SS.ground 0.0
set_voltage -object_list  slice_3/SS.ground 0.0
set_voltage -object_list  slice_4/SS.ground 0.0
set_voltage -object_list  slice_5/SS.ground 0.0
set_voltage -object_list  slice_6/SS.ground 0.0
set_voltage -object_list  slice_7/SS.ground 0.0
set_voltage -object_list  slice_8/SS.ground 0.0
set_voltage -object_list  slice_9/SS.ground 0.0
set_voltage -object_list  slice_10/SS.ground 0.0
set_voltage -object_list  slice_11/SS.ground 0.0
set_voltage -object_list  slice_12/SS.ground 0.0
set_voltage -object_list  slice_13/SS.ground 0.0
set_voltage -object_list  slice_14/SS.ground 0.0
set_voltage -object_list  slice_15/SS.ground 0.0
set_voltage -object_list  slice_16/SS.ground 0.0
set_voltage -object_list  slice_17/SS.ground 0.0
set_voltage -object_list  slice_18/SS.ground 0.0
set_voltage -object_list  slice_19/SS.ground 0.0
set_voltage -object_list  slice_20/SS.ground 0.0
set_voltage -object_list  slice_21/SS.ground 0.0
set_voltage -object_list  slice_22/SS.ground 0.0
set_voltage -object_list  slice_23/SS.ground 0.0
set_voltage -object_list  slice_24/SS.ground 0.0
set_voltage -object_list  slice_25/SS.ground 0.0
set_voltage -object_list  slice_26/SS.ground 0.0
set_voltage -object_list  slice_27/SS.ground 0.0
set_voltage -object_list  slice_28/SS.ground 0.0
set_voltage -object_list  slice_29/SS.ground 0.0
set_voltage -object_list  slice_30/SS.ground 0.0
set_voltage -object_list  slice_31/SS.ground 0.0



set_voltage -object_list  SSL_SIPO_SLICE_SW.power 0.78
set_voltage -object_list  SSL_PISO_SLICE_SW.power 0.78
set_voltage -object_list  slice_0/SSL.power 0.78
set_voltage -object_list  slice_0/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_0/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_1/SSL.power 0.78
set_voltage -object_list  slice_1/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_1/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_2/SSL.power 0.78
set_voltage -object_list  slice_2/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_2/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_3/SSL.power 0.78
set_voltage -object_list  slice_3/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_3/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_4/SSL.power 0.78
set_voltage -object_list  slice_4/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_4/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_5/SSL.power 0.78
set_voltage -object_list  slice_5/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_5/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_6/SSL.power 0.78
set_voltage -object_list  slice_6/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_6/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_7/SSL.power 0.78
set_voltage -object_list  slice_7/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_7/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_8/SSL.power 0.78
set_voltage -object_list  slice_8/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_8/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_9/SSL.power 0.78
set_voltage -object_list  slice_9/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_9/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_10/SSL.power 0.78
set_voltage -object_list  slice_10/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_10/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_11/SSL.power 0.78
set_voltage -object_list  slice_11/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_11/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_12/SSL.power 0.78
set_voltage -object_list  slice_12/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_12/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_13/SSL.power 0.78
set_voltage -object_list  slice_13/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_13/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_14/SSL.power 0.78
set_voltage -object_list  slice_14/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_14/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_15/SSL.power 0.78
set_voltage -object_list  slice_15/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_15/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_16/SSL.power 0.78
set_voltage -object_list  slice_16/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_16/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_17/SSL.power 0.78
set_voltage -object_list  slice_17/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_17/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_18/SSL.power 0.78
set_voltage -object_list  slice_18/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_18/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_19/SSL.power 0.78
set_voltage -object_list  slice_19/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_19/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_20/SSL.power 0.78
set_voltage -object_list  slice_20/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_20/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_21/SSL.power 0.78
set_voltage -object_list  slice_21/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_21/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_22/SSL.power 0.78
set_voltage -object_list  slice_22/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_22/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_23/SSL.power 0.78
set_voltage -object_list  slice_23/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_23/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_24/SSL.power 0.78
set_voltage -object_list  slice_24/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_24/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_25/SSL.power 0.78
set_voltage -object_list  slice_25/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_25/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_26/SSL.power 0.78
set_voltage -object_list  slice_26/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_26/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_27/SSL.power 0.78
set_voltage -object_list  slice_27/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_27/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_28/SSL.power 0.78
set_voltage -object_list  slice_28/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_28/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_29/SSL.power 0.78
set_voltage -object_list  slice_29/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_29/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_30/SSL.power 0.78
set_voltage -object_list  slice_30/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_30/SSL_PISO_SW.power 0.78
set_voltage -object_list  slice_31/SSL.power 0.78
set_voltage -object_list  slice_31/SSL_SIPO_SW.power 0.78
set_voltage -object_list  slice_31/SSL_PISO_SW.power 0.78



set_voltage -object_list  slice_0/SS.power 0.85
set_voltage -object_list  slice_1/SS.power 0.85
set_voltage -object_list  slice_2/SS.power 0.85
set_voltage -object_list  slice_3/SS.power 0.85
set_voltage -object_list  slice_4/SS.power 0.85
set_voltage -object_list  slice_5/SS.power 0.85
set_voltage -object_list  slice_6/SS.power 0.85
set_voltage -object_list  slice_7/SS.power 0.85
set_voltage -object_list  slice_8/SS.power 0.85
set_voltage -object_list  slice_9/SS.power 0.85
set_voltage -object_list  slice_10/SS.power 0.85
set_voltage -object_list  slice_11/SS.power 0.85
set_voltage -object_list  slice_12/SS.power 0.85
set_voltage -object_list  slice_13/SS.power 0.85
set_voltage -object_list  slice_14/SS.power 0.85
set_voltage -object_list  slice_15/SS.power 0.85
set_voltage -object_list  slice_16/SS.power 0.85
set_voltage -object_list  slice_17/SS.power 0.85
set_voltage -object_list  slice_18/SS.power 0.85
set_voltage -object_list  slice_19/SS.power 0.85
set_voltage -object_list  slice_20/SS.power 0.85
set_voltage -object_list  slice_21/SS.power 0.85
set_voltage -object_list  slice_22/SS.power 0.85
set_voltage -object_list  slice_23/SS.power 0.85
set_voltage -object_list  slice_24/SS.power 0.85
set_voltage -object_list  slice_25/SS.power 0.85
set_voltage -object_list  slice_26/SS.power 0.85
set_voltage -object_list  slice_27/SS.power 0.85
set_voltage -object_list  slice_28/SS.power 0.85
set_voltage -object_list  slice_29/SS.power 0.85
set_voltage -object_list  slice_30/SS.power 0.85
set_voltage -object_list  slice_31/SS.power 0.85
