MAPPING_FILE:  ./lib/tech/milkyway/saed32nm_tf_itf_tluplus.map
CORNERS_FILE: scripts/star_config.smc
SELECTED_CORNERS:FUNC_078.FUNC_0.78V_SETUP
REDUCTION: NO_EXTRA_LOOPS
NETLIST_NODE_SECTION: YES
NETLIST_NAME_MAP: YES
NETLIST_FORMAT: SPEF
NETLIST_COMPRESS_COMMAND: /bin/gzip
POWER_EXTRACT: NO
SKIP_CELLS: *
METAL_FILL_POLYGON_HANDLING: IGNORE
INSTANCE_PORT: SUPERCONDUCTIVE
COUPLE_TO_GROUND: NO
REFERENCE_DIRECTION: NONE
COUPLING_THRESHOLD_OPERATION: AND
DPT: NO
COUPLING_ABS_THRESHOLD: 3e-15
COUPLING_REL_THRESHOLD: 0.03
EXTRA_GEOMETRY_INFO: NODE 
POWER_NETS:  VSS VDD VDDH
NDM_DATABASE: ./bit_top.nlib
BLOCK: bit_top/route_opt 
STAR_DIRECTORY: star_bit_top 
NETLIST_FILE: outputs_icc2/star_bit_top.spef
NUM_CORES: 8
STARRC_DP_STRING: list localhost:8
