connect_supply_net -ports U210/VDDG VDDL
connect_supply_net -ports U215/VDDG VDDL
connect_supply_net -ports U228/VDDG VDDL
connect_supply_net -ports U244/VDDG VDDL
connect_supply_net -ports U252/VDDG VDDL
connect_supply_net -ports U264/VDDG VDDL
connect_supply_net -ports U241/VDDG VDDL
connect_supply_net -ports U223/VDDG VDDL
connect_supply_net -ports U205/VDDG VDDL
connect_supply_net -ports U279/VDDG VDDL
connect_supply_net -ports U250/VDDG VDDL
connect_supply_net -ports U211/VDDG VDDL
connect_supply_net -ports U225/VDDG VDDL
connect_supply_net -ports U212/VDDG VDDL
connect_supply_net -ports U237/VDDG VDDL
connect_supply_net -ports U257/VDDG VDDL
