BLOCK: change_names_icc
MILKYWAY_DATABASE: lib_commit_dp
MAGNIFICATION_FACTOR: 1
TCAD_GRD_FILE: tech/star_rcxt/saed32nm_1p9m_Cmax.nxtgrd
MAPPING_FILE: tech/milkyway/saed32nm_tf_itf_tluplus.map
EXTRACTION: RC
TARGET_ANALYSIS: NONE
COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
OPERATING_TEMPERATURE: 25
STAR_DIRECTORY: STARRC
NETLIST_FILE: ./results/star.spef
NETLIST_FORMAT: SPEF

